### ISSUE TITLE
Fix Companion docs

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1207]
Fix: https://docs.ipfs.tech/how-to/companion-node-types/#external

- [x] Clarify External means kubo.
- [x] Remove Embedded till ready to be replaced via helia.
- [x] Fix: https://github.com/ipfs/ipfs-docs/blob/main/docs/install/ipfs-companion.md

**Comment by BigLep** [comment]
> Remove Embedded till ready to be replaced via helia

This is tagged under "Fix companion docs" but this is bigger than docs right?  We're also talking about removing code here.  Your call, but this seems like its own issue providing some justification (linking to js-ipfs deprecation issue) with PR of code removal doc changes linked to it.

I think we should do this before we ship MV3.

**Comment by BigLep** [comment]
> Clarify External means kubo.

Instead of "Set to "External" to connect to a local node using the HTTP API." how about 'Set to "External" to connect to a local Kubo node using the [Kubo RPC API](https://docs.ipfs.tech/reference/kubo/rpc/)."

Anytime we see "HTTP API" we should be fixing to disambiguate between the HTTP Gateway API and the Kubo RPC API.

**Comment by BigLep** [comment]
Other things regarding "API" in the settings screen

API → Kubo RPC API

**Comment by BigLep** [comment]
@whizzzkid: I want to make sure you saw my comments that were added after merge: https://github.com/ipfs/ipfs-companion/pull/1230#pullrequestreview-1523136268
