### ISSUE TITLE
Issue with standard --fix

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-companion#390]
`npm run lint:standard` calls `standard --fix`. This is surprising when the pre-push hook runs this, pushes to your branch and leaves your workspace with changes.

I vote we just run `standard` without `--fix` in `npm run lint:standard` and leave it to the developer to call `npx standard --fix` if they want standard to auto fix the errors.

**Comment by lidel** [comment]
What if we do it the other way around:
leave `--fix` by default, but make pre-push hook run without `--fix`  ? 

That way we have less friction :)

**Comment by alanshaw** [comment]
I think it's still surprising. If I `npm run lint`, I have to know in advance that the "fix" feature exists and that it might alter my files when the command is run.

I'd be ok with adding a `lint:standard:fix` script that doesn't get run by the `lint` script by default?

Typing `npm run lint:standard:fix` is more verbose than `npx standard --fix` so I didn't originally suggest it.

**Comment by olizilla** [comment]
I feel more comfortable if the tools tell me what's wrong, rather than changing things automagically. I vote for doing as little as possible in pre-push. In general I find it more calming to have nothing run pre-push, and have CI let me know if i forgot to do something, so I can deliberately push a work in progress if needs be.
