### ISSUE TITLE
ipfs:// not supported in XMLHttpRequest

### ISSUE THREAD

**Issue by darkdrgn2k** [ipfs-shipyard/ipfs-companion#493]
Seems companion does not process ipfs XMLHttpRequest requests.

Created a simple test:
http://node2.e-mesh.net/ipfstest.html

**Comment by lidel** [comment]
Yes, you are correct. This is because there is no native handler for `ipfs://` (yet).
For now an address of HTTP Gateway can be used, it will be opportunistically redirected by the extension if possible.

_(I am closing this issue, as we are tracking this effort already in https://github.com/ipfs-shipyard/ipfs-companion/issues/164, feel free to subscribe to that one for updates)_
