### ISSUE TITLE
No longer works in Firefox Nightly

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-companion#622]
The IPFS Companion stopped working one–three weeks ago in [Firefox Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/).

It can’t connect to IPFS Desktop anymore. IPFS is listening on the expected ports, however. IPFS Companion still works in Chromium.

I’ve tried reinstalling IPFS Companion and  have tested with older versions all the way back to 2.4.0.

Confirmed issue on Firefox Nightly on macOS 10.14 and Windows 10.1809.

**Comment by da2x** [comment]
OK, the admin interface is returning 403 Forbidden.

The difference between Chrome and Firefox is that Firefox appends a `Origin: moz-extension://{extension-installation-id}` header. If I remove that header in Firefox, everything starts working again.

**Comment by lidel** [comment]
Thank you for reporting!

Interesting. This is basically Firefox version of https://github.com/ipfs-shipyard/ipfs-companion/issues/615 (which we fixed in https://github.com/ipfs-shipyard/ipfs-companion/pull/616).

In short, Chrome was adding `Origin: null` to fetch made from webextension background pages and acted as sort of false-positive trigger for CORS validation producing `403 Forbidden`. 

Seems that Firefox Nightly started setting `Origin: moz-extension://{extension-installation-id}` (which is [better than `null`](https://github.com/ipfs-shipyard/ipfs-companion/pull/616#issuecomment-436997104)) but that produces the same error.  Will probably should apply similar fix here.

**Comment by da2x** [comment]
Heads up: I’d expect this behavior to change in Firefox. The internal UUID they send is unique and persistent per installation. It would allow for user tracking.

**Comment by da2x** [comment]
Correction: it’s been like this for a year according to [bugz#1405971](https://bugzilla.mozilla.org/show_bug.cgi?id=1405971). I’m not sure why this issue only started affecting IPFS now.

**Comment by lidel** [comment]
@da2x  shipped a fix in [v2.6.1.12130](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.6.1.12130) (Beta), give it a try! :)

**Comment by da2x** [comment]
Works for me.
