### ISSUE TITLE
Content-Security-Policy (CSP) warning

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-companion#624]
Visit a web page with a strict CSP such as `Content-Security-Policy: default-src: none`. (This works as a [test page](https://email.ctrl.blog/).)

The extension generates a console error message:

    Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).

I have a ton of extensions with content scripts installed, and this is the only one that triggers CSP warnings. I’ve not analyzed what IPFS Companion is doing that causes the warning.

Firefox Nightly 65.0a1 (2018-11-16)

**Comment by lidel** [comment]
Good catch @da2x! 

I am quite sure this is caused by `window.ipfs` experiment, which injects API via customized instance of [ipfs-postmsg-proxy](https://github.com/tableflip/ipfs-postmsg-proxy). We will look into this warning as a part of #589 and [milestone/15](https://github.com/ipfs-shipyard/ipfs-companion/milestone/15).

For now, try disabling it on _Preferences_ screen:

> ![2018-11-21--18-36-35](https://user-images.githubusercontent.com/157609/48858760-7b1e0680-edbc-11e8-882f-f72cb3dccb81.png)

The error should go away.

**Comment by lidel** [comment]
Closing due to https://github.com/ipfs-shipyard/ipfs-companion/issues/589#issuecomment-712356448
