### ISSUE TITLE
add to ipfs dont get html images and css

### ISSUE THREAD

**Issue by icf20** [ipfs-shipyard/ipfs-companion#699]
i was testing this function and i dont know if there is a limitation or something is to avoid duplication of content ?

**Comment by lidel** [comment]
I assume you right-clicked on HTML page and selected "Add to IPFS" ?

Yes, so that only saves the HTM alone.
If assets used on the page are refered using relative paths they won't load anymore. 

I am closing this one, as mirroring "full page snapshot" (with images, CSS etc) is already tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/91#issuecomment-475707708
