### ISSUE TITLE
SeaMonkey support

### ISSUE THREAD

**Issue by Mikaela** [ipfs-shipyard/ipfs-companion#702]
I was talking about IPFS with a SeaMonkey user yesterday and found out that addons aren't directly compatible. Would IPFS Companion be able to support SeaMonkey easily?

* [Download page with anchor for 64bit build](https://www.seamonkey-project.org/releases/#contrib) (I was confused by everything else being 32bit which refused to start on my Debian 10/testing 64-bit)
* [SeaMonkey/Firefox differences](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/SeaMonkey_2) (from the link below)
* [Addon converter that fails for IPFS Companion](http://addonconverter.fotokraina.com/convert.php)

**Comment by lidel** [comment]
_(apologies for late response, been traveling afk)_

Unfortunately SeaMonkey does not support WebExtensions architecture used by newer Firefox (and Chromium) versions. It supports the old XUL APIs, which are not supported by our codebase since 2017.

Not sure how useful it is, but the last Companion release from 1.x series might be compatible with SeaMonkey (it used old XUL APIs, so you should be able to convert it using the tool you linked): [v1.6.0](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v1.6.0).

But that is about it. 

I am closing this issue as there are no plans to support XUL again, but the sources of 1.6.0 are in the public domain (CC0), so if someone wants to fork [ipfs-companion/tree/v1.6.0](https://github.com/ipfs-shipyard/ipfs-companion/tree/v1.6.0)  and maintain extension for SeaMonkey, they can :)

**Comment by Mikaela** [comment]
Thanks, I didn't understand that SeaMonkey is using XUL and knowing it I now found [Tracking bug for WebExtensions support in SeaMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1320556), I hope it will make it possible to support IPFS Companion or even makes Firefox extensions work directly.
