### ISSUE TITLE
How to handle Incognito Mode?

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#704]
> For extension developers, Firefox now fully supports the value `not_allowed` for the [manifest `incognito` key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito).  As with Chrome, specifying `not_allowed` in the manifest will prevent the extension from running or receiving events from private windows.
> – https://blog.mozilla.org/addons/2019/03/26/extensions-in-firefox-67/

**Comment by Mikaela** [comment]
I think IPFS Companion shouldn't work with incognito mode. I think if a site uses IPFS, IPFS Companion will request it with the local gateway which (as far as I know of) has no concept of incognito mode so it will store and seed those sites or their content until gc runs (which again is still disabled by default (isn't it?)) and thus potentially leak that the site has been visited while incognito mode isn't supposed to store content locally.

Personally I have disallowed IPFS Companion from running in Firefox private windows, because it makes testing sites loading content from IPFS easier than opening a different browser for it and lately that has been the only time when I seldom use private windows (if I really wanted something to be private I would use Tor Browser).

**Comment by lidel** [comment]
@Mikaela  I agree, due to fingerprinting surface we should disable it in Incognito for now. Would you be up for making a PR that adds proper key to [`manifest.common.json`](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/add-on/manifest.common.json)?

**Comment by lidel** [comment]
Enhanced Privacy Controls in Firefox 67 landed in stable channel.

> _https://hacks.mozilla.org/2019/05/firefox-67-dark-mode-css-webrender/:_
> [![2019-05-23--12-21-09](https://user-images.githubusercontent.com/157609/58245520-43851c80-7d55-11e9-8f27-195a271e28c8.png)](https://hacks.mozilla.org/2019/05/firefox-67-dark-mode-css-webrender/)

I tested this and disabling Companion in incognito using controls provided by the browser works as expected, so old users can do it manually until https://github.com/ipfs-shipyard/ipfs-companion/pull/705 lands.
