### ISSUE TITLE
Changing language around Web UI

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#781]
> #### Changing language around some features 
> 
> We are at the stage where we need to **rework language** around some features provided by IPFS Companion. Current labels describe what happens at the technical level and don't tell much about the purpose unless user is already familiar with low level details of our stack.

## Motivation

"Web UI" doesn't have meaning for IPFS users, only for core developers. 
We should change the way we point users at it in IPFS Companion.

Current state is "Open Web UI" everywhere:

> ![2019-10-02--12-34-35](https://user-images.githubusercontent.com/157609/66037953-10c40f80-e511-11e9-80b7-c25e45b2edec.png)

### Prior art: IPFS Desktop

Does not use "Web UI" anywhere,   but links to  specific screens within Web UI (Status, Files etc)

> ![image](https://user-images.githubusercontent.com/157609/66038071-600a4000-e511-11e9-8023-9cd9b4dffc8e.png)

cc @ericronne @hacdias @autonome

**Comment by hacdias** [comment]
I agree with you @lidel. Saying "Web UI" to users doesn't mean anything and we should change the 'Open Web UI' text on IPFS Companion. I see two alternatives here:

1. **Use a Desktop-like approach**: by this I mean to have multiple links to different sections (Files, Settings, Peers). However, having either 'Settings' or 'Status' could be confusing because they could be mistaken with the extension's settings.
2. **Change the expression 'Web UI'**: 'Open Node Management', 'Open Node Info', 'Open Dashboard'... Perhaps the latter would fit best. Still, I'm not sure if we should call Web UI such a "technical" term.

**Comment by autonome** [comment]
I like the first approach, as it's centered around what the user wants to do. In Lisbon we identified the core use-cases - things people want to do:

* Publish: adding/pinning files and dirs from your local filesystem to your repo
* Saving: downloading or syncing from web/ipfs/other to your local repo
* Viewing: viewing/reading what's in your repo
* Sharing: get reference to what's in your repo, to give to others

Additionally there are technical or administrator use-cases, eg what would go in "Settings" typically, but in our case would also include "Peers" and things like that.

**Comment by jessicaschilling** [comment]
Waking this one up with a update. We've done a good job about referring to which specific parts of Web UI the user is going to rather than just "Web UI" -- but there are still three locations where we are actually referring to Web UI as a whole and will need to settle on a naming convention.

1. In the main menu (technically this could say "Open Status" since it goes to the status page, but that's not the best prompt ... we're really inviting the user into all of Web UI with this option)
![image](https://user-images.githubusercontent.com/1507828/85781053-8648bf00-b6e2-11ea-8a38-d0a45290755c.png)

2. In prefs here:
![image](https://user-images.githubusercontent.com/1507828/85781386-dcb5fd80-b6e2-11ea-8075-667514b47ed3.png)

3. In prefs here:
![image](https://user-images.githubusercontent.com/1507828/85781450-edff0a00-b6e2-11ea-8cee-2a517b03f40a.png)

We've talked elsewhere about perhaps adopting "IPFS Dashboard" as a replacement for "IPFS Desktop", which opens the door to perhaps calling Web UI "IPFS Web Dashboard" or "IPFS Browser Dashboard" as a differentiator.

**Comment by lidel** [comment]
FYI there were prior attempts to rename WebUI: 
- https://github.com/ipfs/ipfs-gui/issues/5 
- https://github.com/ipfs-shipyard/ipfs-webui/issues/612#issuecomment-353508706 (concerns about "Dashboard")

I hoped to avoid the renaming rabbit hole and just make the name _disappear_ (at least in the browser action menu) by providing links to specific screens: just like we did in the new Welcome page:

> ![2020-06-25--23-49-23](https://user-images.githubusercontent.com/157609/85798880-942c2d80-b73e-11ea-9582-f52f0e54aa13.png)

Doing it in current menu will be tricky (limited vertical space), but perhaps we could remove 
 `Open Web UI` menu item and use those freed up pixels for a row buttons below `PEERS`?

**Comment by jessicaschilling** [comment]
Update: I think we're OK to close this issue. In the latest Companion release, "Web UI" has been replaced either by more explicit language ("Go To My Node ..." etc) or by links directly to screens (status/files/peers), with one exception, in the prefs:

![image.png](https://images.zenhubusercontent.com/5ce5bf88b1698b1ceb4ce811/2ee5e7c8-0f92-4a78-bc24-5ef8db4353db)

While the header uses "Web UI", the text clarifies that we're talking about the status, files and peers screens, and specifies that these are coming from webui.ipfs.io: so in this case "Web UI" is actually an accurate description rather than a product shorthand.
