### ISSUE TITLE
Opening .eth creates 2 tabs

### ISSUE THREAD

**Issue by abueide** [ipfs-shipyard/ipfs-companion#873]
**Describe the bug**

when I click on this link: http://ipfs.eth I end up with two tabs: www.ipfs.eth (doesn't load, says it could not connect), and another new tab gets opened to ipfs.eth.link which loads properly. Why is it loading in a new tab instead of redirecting in the old tab? I don't want two tabs every time I click/type in a .eth link. It happens on http://almonit.eth too. Happens in firefox/chrome.

**To Reproduce**
Click on this link with ipfs companion installed in firefox: http://ipfs.eth

**Expected behavior**
A single tab redirecting to ipfs.eth.link, or at least an option to disable ens name resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/19354425/80895634-316d6700-8ca4-11ea-8f62-b5087515900e.png)

**Comment by lidel** [comment]
Original tab fails because browser is unable to connect to the server (`.eth` is not a real TLD).

By default IPFS Companion tries to recover from various HTTP failures by checking for DNSLink record and recovering in a new tab, and that is what you observe here.

That being said, I agree `.eth` is a special case and instead of opening a new tab, we could improve UX by updating URL of original one. 

I suspect the fix is to change [this line](https://github.com/ipfs-shipyard/ipfs-companion/blob/793bd6cdbe804f611ed42f7dd32c6fb8d9d224b8/add-on/src/lib/ipfs-request.js#L383):

```diff
- return createTabWithURL(request, redirectUrl, browser, recoveredTabs)
+ browser.tabs.update({ url: fixedUrl })
+ return
```

@abueide is this something you would be interested in submitting PR for?

**Comment by abueide** [comment]
@lidel sure, I tested it and its working now. Should I replace the ones in the isRecoverable and isRecoverableViaDNSLink functions for the PR as well?

**Comment by lidel** [comment]
@abueide yes, I believe it will be less confusing than having two tabs for now.

Instead of changing this everywhere please:
1.  rename `createTabWithURL` to `updateTabWithURL` and switch its internals to `browser.tabs.update`
2. `recoveredTabs` cache can be removed - no longer needed

Thanks!
