### ISSUE TITLE
Revamp Companion "sales" and overview materials

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#896]
Chrome Web Store is the main user aquisition channel for this browser extension:

- https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch

Current listing is pretty old. It consists of `Overview` text and screenshots.
There are also additional "promo tile" graphics displayed on the store listings (note resolutions):

> ![2020-06-18--14-19-04](https://user-images.githubusercontent.com/157609/85019417-1d57c900-b16f-11ea-83be-52b499c9395d.png)

----

@jessicaschilling as you noted in [IPFS GUI tools: June 2020 survey analysis](https://docs.google.com/document/d/1V5sDSxMqhhplpcB8u8CffiGWHUvw-t4p_sn5vigdR90), a big chunk of users does not feel like they understand what to expect when they install this extension. Perhaps rewriting `Overview` and producing better screenshots (macOS?) could take us 80% where we need to be?

**Comment by jessicaschilling** [comment]
First pass at Chrome Store text below — once we arrive at something more final, can amend/extrapolate for other channels.

Also want to create an ipfs.io link to the privacy policy so we're not asking folks to copy/paste a long GitHub link.

@lidel -- initial thoughts?

**TAGLINE (note this appears in big type at the bottom of the Chrome Store page):**
Harness the power of IPFS in your browser

**BODY:**

IPFS Companion harnesses the power of your locally running IPFS node (either through the IPFS Desktop app or the command-line daemon) directly inside your favorite browser, enabling support for ipfs:// paths, automatic IPFS gateway loading of websites and file paths, easy IPFS file import and sharing, and more.

IPFS is a peer-to-peer hypermedia protocol designed to make the web faster, safer, more resilient, and more open. It enables the creation and dissemination of completely distributed sites and applications that don’t rely on centralized hosting and stay true to the original vision of an open, flat web. Visit https://ipfs.io to learn more.

FEATURES
- Automatically use IPFS to retrieve sites, files, and other resources already stored on IPFS (including redirecting DNSLink hostnames to IPNS names via your choice of gateway)
- Support IPFS paths (ipfs://) in your browser, and redirect them to the gateway of your choice
- Share files from your browser by importing them to your local IPFS node via right-click or drag-and-drop, including the option to preload files at a public gateway
- See how many peers you’re connected to at a glance from your browser’s menu bar
- Check gateway info and API status with a single click
- Common IPFS tasks — like pinning files, copying shareable links/paths/CIDs, and launching your IPFS Web UI dashboard — are available right in your browser
- Options to toggle IPFS redirects globally or per website
- Choose between connecting to your local IPFS node via the HTTP API or running a js-ipfs node directly in your browser

IMPORTANT NOTE
Because IPFS Companion (in its standard configuration) talks to your computer’s local IPFS node to work its browser magic, you’ll need to have IPFS running on your computer, too — either from your terminal or using the friendly, free IPFS Desktop app. Visit https://ipfs.io to learn more and install.

MORE INFO
- Learn about IPFS and how it’s changing the Internet at https://ipfs.io
- See the IPFS Companion privacy policy at https://github.com/ipfs-shipyard/ipfs-companion/blob/master/PRIVACY-POLICY.md

**Comment by lidel** [comment]
Made tiny tweaks in sentences where we mention "ipfs://" but overall looks good, thank you!

I realized that before we publish this, we need two things:

- [ ] https://ipfs.io/privacy/ipfs-companion (see PR https://github.com/ipfs/website/pull/386)
- [ ] email alias `ipfs-companion (at) ipfs.io` for currently visible ugly one in `Additional Information`
  (asked IT, waiting for answer)

**Comment by jessicaschilling** [comment]
@lidel Awesome idea on the Google groups email alias. Thank you for doing both of those things! I'll get some screenshots etc set up for the other elements on the Chrome store page.

**Comment by jessicaschilling** [comment]
ETA: Hugo nonsense = privacy policy URL is now:
http://ipfs.io/companion-privacy

**Comment by lidel** [comment]
Email alias is set up and confirmed to work as expected.

**Comment by jessicaschilling** [comment]
@lidel Awesome -- looks like you've already updated the email address in the Chrome Store dashboard.

I've done the following for both the stable and beta listings, and saved as draft. If you're able to look the drafts over at your leisure and submit for review, that would be awesome:
- Replaced text per the above comment (note I had to PR https://github.com/ipfs-shipyard/ipfs-companion/pull/898 to get the tagline updated, as this is actually in the manifest)
- Updated screenshots
- Updated promo images
- Proofread and copy-edited the privacy messages for clarity

Feel free to submit for review if you think we're good and the time frame for review isn't going to collide with anything else.

Also, if you want to give me Firefox store access, I'll update there too.

**Comment by lidel** [comment]
Thank you! LGTM, I've submitted Beta for review.
If it gets accepted without any problems, will do the same for Stable.

@jessicaschilling You should have access to Firefox store now too.

**Comment by jessicaschilling** [comment]
Firefox updated: https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/

**Comment by lidel** [comment]
Looks great!
In other news, updated Beta got approved by Google, I've submitted Stable.

**Comment by jessicaschilling** [comment]
Repo readme is ready for @lidel review under https://github.com/ipfs-shipyard/ipfs-companion/pull/899 ... and then we can call this one cooked 😊
