### ISSUE TITLE
Include assets when we do "right click > import on ipfs" on a website

### ISSUE THREAD

**Issue by hazae41** [ipfs-shipyard/ipfs-companion#948]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I right click a website to import it to IPFS, but only the html is imported

**Describe the solution you'd like**
The user expects to get the page and its assets: favicon, css, js, images, etc

**Comment by jessicaschilling** [comment]
Hi @hazae41 - afraid this is a known issue that's been around for a while: see https://github.com/ipfs-shipyard/ipfs-companion/issues/91. There are some tricky details that turn this into a larger problem that the core team unfortunately can't take on at this time due to bandwidth limitations, but community contribution to make this a reality would be more than welcome.

(Closing this instance as a duplicate.)
