### ISSUE TITLE
Origin header set to null causing 403 by IPFS API

### ISSUE THREAD

**Issue by benaryorg** [ipfs-shipyard/ipfs-companion#955]
# Describe the bug

There seems to be a regression akin to #622.
On my Windows box with Firefox 85.0b4 (not on the Linux one with 84.0.1 though) this has persisted for some time (a week or two?).
Checking the debugging tools the Windows box sends `Origin: null` (being rejected by IPFS with a 403, unless I add "null" as a CORS domain, my current workaround) while the Linux box still sends `Origin: http://127.0.0.1:5001`.

# To Reproduce

1. stock settings seem to suffice, but only on that box?

# Expected behavior

I'd expect the origin to match the localhost-ish domain, thereby passing the validation.

# Desktop

| | |
|:--|:--|
| OS | Windows 10 |
| Browser | Firefox 85.0b4 |
| IPFS Companion Version | 2.16.0 |

**Comment by jessicaschilling** [comment]
Thanks - we'll look in more detail in our next triage session.

**Comment by lidel** [comment]
I'll look deeper into this in next two weeks, but can confirm something changed in Firefox. 
XHR request made to IPFS API is now sent with different set of headers: not only `Origin`, but also `Sec-` ones:

| Firefox 84  (OK) | Firefox 86.0a1  (403 Forbidden) | 
| ---- | ---- |
| ![2021-01-02--02-11-20](https://user-images.githubusercontent.com/157609/103448881-05294080-4ca0-11eb-993c-a43ab594aaac.png)  | ![2021-01-02--02-11-42](https://user-images.githubusercontent.com/157609/103448882-0b1f2180-4ca0-11eb-9967-54fda886f191.png)  | 


In 2018, we had similar issues related to the way browsers handle XHR HTTP requests sent from the background page of our browser extension (https://github.com/ipfs-shipyard/ipfs-companion/issues/622, https://github.com/ipfs-shipyard/ipfs-companion/pull/616), this could be Firefox trying to align with what Chromium does, or a bug (or both).

Additional research is needed, but I'm marking this as P0 because if breaks Companion in  Firefox > 85.0b4.

**Comment by lidel** [comment]
@benaryorg @fellowish

A fix for Firefox 85+ shipped to Beta channel: [v2.16.0.990](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.16.0.990).
Let us know if you experience any issues. Thanks again for reporting this!
